### PR TITLE
Massive Refactor

### PR DESCRIPTION
**Pull request by perploug**
# Refactor

- Rewrites the library as correct JS modules
- Abstracts out the github and db clients
- each type of data fetched now has its own class

- Fixes issues with hiddden exceptions
- Correctly stores all data now
- 40% speed increase
- Better CLI output
- Consistent contributor stats
- Outputs stats and datestamped stats
- Supports passing in the specific orgs you wish to query as a parameter

    node run.js TOKEN ORG,ORG,ORG

### CODE REVIEW

**Comment by perploug** [comment]
merged and ready for review

**Comment by baggerspion** [comment]
Does not run in the following env:
- node v8.11.4
- npm  v5.8.0

**Comment by perploug** [comment]
Any errors / exceptions?

**Comment by perploug** [comment]
on 8.11.1 and npm 5.6.0 it works - should not be any breaking changes between those versions

**Comment by perploug** [comment]
@therealpadams your forgot to approve and merge! :)

**Review by baggerspion — APPROVED** [review]

**Pull request merged**
